### ISSUE TITLE
Passing unknown --x-oftr-args to oftr should fail faster and cleaner

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/pylibofp#2]
```bash
$ python -m zof.demo.lameduck --x-oftr-args='trace=rpc'
jsonrpc: Unknown command line argument 'trace=rpc'.  Try: 'jsonrpc -help'
Sep 26 13:42:52.706 zof    ERROR    Unable to get description from oftr [TimeoutException xid=8093 timeout=10.0]
Sep 26 13:42:52.708 zof    ERROR    Exception in Controller._start
Traceback (most recent call last):
  File "/Users/bfish/code/pylibofp/zof/controller.py", line 176, in _start
    await self._get_description()
  File "/Users/bfish/code/pylibofp/zof/controller.py", line 194, in _get_description
    result = await self.rpc_call('OFP.DESCRIPTION')
zof.exception.TimeoutException: [TimeoutException xid=8093 timeout=10.0]
Sep 26 13:42:52.712 zof    ERROR    oftr exited with return code 1
Sep 26 13:42:52.713 zof    INFO     Exiting with status 11
```

**Comment by byllyfish** [comment]
Fixed in v0.10.0
